export const MAIN_ROUTE = '/'
export const TECHNIC_ROUTE ='/technic'
export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const LK_ROUTE = '/lk'
export const PAY_ROUTE = '/pay'